routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'Auth\LoginController@index')->name('');

//dashboard
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoriesController');
Route::resource('products', 'ProductsController');
Route::resource('transactions', 'TransactionsController');
Route::resource('shop', 'ShopController');

//add admin
Route::get('addadmin', [
	'uses' => 'HomeController@addAdmin',
	'as' => 'addadmin'
]);

Route::post('registeradmin', [
	'uses' => 'HomeController@registerAdmin',
	'as' => 'registeradmin'
]);	

//my profile
Route::get('myprofile', [
	'uses' => 'HomeController@myProfile',
	'as' => 'myprofile'
]);

Route::post('admineditprofile', [
	'uses' => 'HomeController@editMyProfile',
	'as' => 'admineditprofile'
]);

Route::post('adminchangepassword', [
	'uses' => 'HomeController@changePassword',
	'as' => 'adminchangepassword'
]);

//category

Route::get('/restorecategory/{id}', [
	'uses' => 'CategoriesController@restoreCategory',
	'as' => 'restorecategory'
]);

//products
Route::post('/update_image', 'ProductsController@updateImage')->name('update_image');

Route::get('exportproduct', [
	'uses' => 'ProductsController@exportProduct',
	'as' => 'exportproduct'
]);

Route::post('importexcel', [
	'uses' => 'ProductsController@importExcelfile',
	'as' => 'importexcel'
]);

Route::post('processexcel', [
	'uses' => 'ProductsController@processExcelfile',
	'as' => 'processexcel'
]);

Route::get('/restore/{id}', [
	'uses' => 'ProductsController@restoreProduct',
	'as' => 'restore'
]);

Route::get('/addstock_view/{id}', [
	'uses' => 'ProductsController@viewAddStock',
	'as' => 'addstock_view'
]);

Route::post('addstock', [
	'uses' => 'ProductsController@addStockProduct',
	'as' => 'addstock'
]);

//////////////////////////////////////////////////////////////
//customers
Route::get('customers', [
	'uses' => 'CustomersController@getIndex',
	'as' => 'customers'
]);

Route::post('sendmessage', [
	'uses' => 'CustomersController@sendCustomerEmail',
	'as' => 'sendmessage'
]);

////////////////////////////////////////////////////////////

//orders 
Route::get('orders', [
	'uses' => 'OrdersController@getIndex',
	'as' => 'orders'
]);

Route::get('/processorder/{id}', [
	'uses' => 'OrdersController@processOrder',
	'as' => 'processorder'
]);

Route::get('/deliverorder/{id}', [
	'uses' => 'OrdersController@deliverOrder',
	'as' => 'deliverorder'
]);

Route::get('/rejectorder/{id}', [
	'uses' => 'OrdersController@rejectOrder',
	'as' => 'rejectorder'
]);

Route::get('sendemail', [
	'uses' => 'OrdersController@sendEmail',
	'as' => 'sendemail'
]);

Route::get('/notify/{pid}/{oid}', [
	'uses' => 'OrdersController@notifyOutOfStock',
	'as' => 'notify'
]);

//////////////////////////////////////////////////////////////

//reports
Route::get('reports',[
	'uses' => 'ReportsController@getIndex',
	'as' => 'reports'
]);

Route::post('showreports', [
	'uses' => 'ReportsController@generateReport',
	'as' => 'showreports'
]);

Route::get('/printreport/{datefrom}/{dateto}', [
	'uses' => 'ReportsController@printReport',
	'as' => 'printreport'
]);

Route::get('printreporttoday', [
	'uses' => 'ReportsController@printReportToday',
	'as' => 'printreporttoday'
]);



///////////////////////////////////////////////////////////////
// shop
Route::get('/add-to-cart/{id}', [
	'uses' => 'ShopController@getAddToCart',
	'as' => 'product.addToCart'
]);

Route::get('/addByOne/{id}', [
	'uses' => 'ShopController@getAddByOne',
	'as' => 'product.addByOne'
]);

Route::get('/reduceByOne/{id}', [
	'uses' => 'ShopController@getReduceByOne',
	'as' => 'product.reduceByOne'
]);

Route::get('/remove/{id}', [
	'uses' => 'ShopController@getRemoveItem',
	'as' => 'product.revomeItem'
]);

Route::get('/shopping-cart', [
	'uses' => 'ShopController@getCart',
	'as' => 'product.shoppingCart'
]);

Route::get('/checkout', [
	'uses' => 'ShopController@getCheckout',
	'as' => 'checkout',
	'middleware' => 'auth'
]);

Route::post('/checkout', [
	'uses' => 'ShopController@saveOrder',
	'as' => 'checkout'
]);

Route::post('/cancelorder', [
	'uses' => 'ShopController@cancelOrder',
	'as' => 'cancelorder'
]);

Route::get('/vieworder/{id}', [
	'uses' => 'ShopController@viewOrderList',
	'as' => 'order.vieworder'
]);

Route::get('/category/{id}', [
	'uses' => 'ShopController@filterByCategory',
	'as' => 'shop.category'
]);

Route::post('editprofile', [
	'uses' => 'ShopController@updateProfile',
	'as' => 'editprofile'
]);

Route::post('customerchangepassword', [
	'uses' => 'ShopController@changePassword',
	'as' => 'customerchangepassword'
]);

Route::get('indicatorverify', [
	'uses' => 'ShopController@indicatorVerify',
	'as' => 'indicatorverify'
]);

Route::group(['prefix' => 'user'], function() {

	Route::group(['middleware' => 'guest'], function() {

		Route::get('/customer_register', [
			'uses' => 'ShopController@customerRegister',
			'as' => 'user.customer_register',
		]);

		Route::post('/customer_signup', [
			'uses' => 'ShopController@customerSignup',
			'as' => 'user.customer_signup',
		]);

		Route::get('/customer_login', [
			'uses' => 'ShopController@customerLogin',
			'as' => 'user.customer_login',
		]);

		Route::post('/customer_signin', [
			'uses' => 'ShopController@customerSignin',
			'as' => 'user.customer_signin',
		]);

		Route::get('/verifyaccount/{id}', [
			'uses' => 'ShopController@verifyAccount',
			'as' => 'user.verifyaccount'
		]);

	});
	
	Route::group(['middleware' => 'auth'], function() {

		Route::get('/customer_logout', [
			'uses' => 'ShopController@customerLogout',
			'as' => 'user.customer_logout',
		]);

		Route::get('/customer_orders', [
			'uses' => 'ShopController@customerOrders',
			'as' => 'user.customer_orders',
		]);

		Route::get('/customer_profile', [
			'uses' => 'ShopController@customerProfile',
			'as' => 'user.customer_profile',
		]);

	});

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    //
    use SoftDeletes;

    protected $fillable = [
    	'name',
    	'description',
    	'user_id',
    ];

    protected $dates = ['deleted_at'];

    public function products() {
    	return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Auth;
use DB;
use App\Product;

class CategoriesController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth');  
    }
    public function index()
    {
        //
        if (Auth::user()->role_id == 1) {

            $categories = Category::whereNull('deleted_at')
                            ->get();

            $trashcategory = DB::table('categories')
                                ->whereNotNull('deleted_at')
                                ->get();

            $counterorder = DB::table('transactions')
                            ->where('status', "Pending")
                            ->count();

            return view('categories.index', ['categories' => $categories, 'counterorder' => $counterorder, 'trashcategory' => $trashcategory]);
            
        }
        return back();
    }

    public function store(Request $request)
    {
        //
        if (Auth::user()->role_id == 1) {

            $category = Category::create([
                            'name' => $request['name'],
                            'description' => $request['description'],
                            'user_id' => Auth::user()->id,
                        ]);

            if ($category) {
                return back()->with('success','Category added successfully');
            }
            return back()->with('errors','Error adding category');

        }
        return back();

    }


    public function edit(Category $category)
    {
        //
        if (Auth::user()->role_id == 1) {
            $findCategory = Category::find($category->id);
            $counterorder = DB::table('transactions')
                            ->where('status', "Pending")
                            ->count();
            return view('categories.edit', ['category' => $category, 'counterorder' => $counterorder]);
        }
        return back();
    }

    public function update(Request $request, Category $category)
    {
        //
        if (Auth::user()->role_id == 1) {
            $updateCategory = Category::where('id', $category->id)
                            ->update([
                                'name' => $request['name'],
                                'description' => $request['description'],
                            ]);

            if ($updateCategory) {
                return back()->with('success','Category updated successfully');
            }
            return back()->with('errors','Error updating category');
        }
        return back();
    }

    public function destroy(Category $category)
    {
        //
        if (Auth::user()->role_id == 1) {
            $findCategory = Category::find($category->id);

            if ($findCategory->delete()) {

                $products = Product::where('id', $category->id)
                                    ->get();

                foreach ($products as $product) {
                    $trashProduct = Product::where('category_id', $category->id)
                                            ->delete();
                }
                return back()->with('success' , 'Category deleted successfully');
            }
            return back()->withInput()->with('errors', 'Error deleting category');
        }
        return back();
    }

    public function restoreCategory($id)
    {
        if (Auth::user()->role_id == 1) {
            $findCategory = Category::where('id', $id)
                                    ->restore();

            if ($findCategory) {
                return back()->with('success' , 'Category restored successfully');
            }
            return back()->withInput()->with('errors', 'Error restore category');
        }
        return back();
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')

	@include('partials.sidebar')

	<main role="main" class="col-md-9 col-lg-9 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

		@include('partials.errors')
        @include('partials.success') 

		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
		  <h1 class="h2"><a href="/categories"><i class="fa fa-list"></i> Categories/</a>Update category</h1>
		</div>

		<div class="container">
      <div class="row">
          <div class="col-md-8 mt-5">

            <form method="post" action="{{ route('categories.update', [$category->id]) }}">
            <input type="hidden" name="_method" value="put">
            @csrf
            <div class="row">
                                   
                <div class="col-md-5">
                  <div class="form-group">
                    <label for="id" class="col-form-label">Category ID:</label>
                    <input type="text" class="form-control bg-white" id="id" value="{{ $category->id }}" readonly disabled>
                  </div>
                </div>

                <div class="col-md-8">
                  <div class="form-group">
                    <label for="category-name" class="col-form-label">Category name:</label>
                    <input type="text" class="form-control bg-white" name="name" id="category-name" value="{{ $category->name }}" placeholder="Category name" required>
                  </div>
                </div>            

                <div class="col-md-8">
                  <div class="form-group">
                    <label for="address-text" class="col-form-label">Description:</label>
                    <textarea class="form-control bg-white" rows="4" name="description" id="desciption" placeholder="Description">{{ $category->description }}</textarea>
                  </div>
                </div>


                <div class="col-md-12">
                    <div class="form-group float-right">
                      <button class="btn btn-primary float-right" type="submit"><i class="fa fa-arrow-down"></i> Save</button>
                    </div>
                </div>

              </div>
            </form>

          </div>

      </div>            
    </div>

	  
	</main>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

	@include('partials.sidebar')

	<main role="main" class="col-md-9 col-lg-9 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

		@include('partials.errors')
        @include('partials.success') 

	  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
	    <h1 class="h2"><i class="fa fa-list"></i> Categories</h1>
	    <div class="btn-toolbar mb-2 mb-md-0">
	      <div class="btn-group mr-2">
	        <button class="btn btn-primary p-3" data-toggle="modal" data-target=".add-category"><i class="fa fa-plus"></i> Add Category</button>
          <button class="btn btn-warning p-3 text-white" data-toggle="modal" data-target=".trashed"><i class="fa fa-trash-o"></i> Trashed</button>
	      </div>
	    </div>
	  </div>

	  <div class="table-responsive">
        <table class="table table-striped table-sm" id="table">
          <thead>
            <tr>
              <th>Category ID</th>
              <th>Name</th>
              <th width="200px">Description</th>
              <th width="200px">Action</th>
            </tr>
          </thead>
          <tbody>
          	@foreach($categories as $category)
            <tr>
              <td>{{ $category->id }}</td>
              <td>{{ $category->name }}</td>
              <td>
              		<textarea class="form-control" rows="3" readonly>{{ $category->description }}</textarea></td>
              <td>
	                <a class="btn btn-primary" href="/categories/{{$category->id}}/edit"><i class="fa fa-pencil-square-o"></i> Edit</a> &nbsp;
	                <button class="btn btn-danger" data-toggle="modal" data-target=".delete{{$category->id}}"><i class="fa fa-times"></i> Delete</button>

                    <!-- Modal -->
                    <div class="modal fade bd-example-modal-lg delete{{$category->id}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-md modal-dialog-centered">
                        <div class="modal-content">

                          <div class="modal-header bg-danger">
                            <h6 class="modal-title text-white" id="exampleModalLabel">Delete category</h6>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>

                          <div class="modal-body">
                            Are you sure do you want to delete category?
                          </div>

                          <div class="modal-footer">
                             <form id="delete-form" action="{{ route('categories.destroy', [$category->id]) }}" 
                              method="POST">
                                  <input type="hidden" name="_method" value="delete">
                                      @csrf
                                  <button type="submit" class="btn btn-primary">Yes</button>
                            </form> 
                            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                          </div>

                        </div>
                      </div>
                    </div>
                    <!--  End modal -->
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
	</main>

	<!-- Large modal -->
	<div class="modal fade bd-example-modal-lg add-category" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-lg" role="document">
	    <div class="modal-content">
	      <div class="modal-header bg-primary text-white">
	        <h5 class="modal-title" id="exampleModalLabel">Add category</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	      	<form method="post" action="{{ route('categories.store') }}">
              @csrf

              <div class="col-md-12">
                <div class="row">

	                  <div class="col-md-8">
	                    <div class="form-group">
	                      <label for="category-name" class="col-form-label">Category Name:</label>
	                      <input type="text" class="form-control" id="category-name" name="name" placeholder="Category name" required>
	                    </div>
	                  </div>

	                  <div class="col-md-8">
	                    <div class="form-group">
	                      <label for="description" class="col-form-label">Description:</label>
	                      <textarea class="form-control" rows="4" id="description" name="description" placeholder="Description" required></textarea>
	                    </div>
	                  </div>

                </div>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                <button type="submit" class="btn btn-primary"><i class="fa fa-arrow-down"></i> Save</button>
              </div>

            </form>
	      </div>
	    </div>
	  </div>
	</div>

  <!-- Large modal / trash category- -->
  <div class="modal fade bd-example-modal-lg trashed" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header bg-warning text-white">
          <h5 class="modal-title" id="exampleModalLabel">Deleted category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

          <table class="table table-striped table-sm" id="tableTrashed">
            <thead>
              <tr>
                <th>Category ID</th>
                <th>Name</th>
                <th>Description</th>
                <th width="180px">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($trashcategory as $category)
              <tr>
                <td>{{ $category->id }}</td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->description }}</td>
                <td>
                    <a class="btn btn-success" href="{{ route('restorecategory', ['id' => $category->id]) }}"><i class="fa fa-chevron-down"></i> Restore</a> &nbsp;
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
          
        </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
          </div>
      </div>
    </div>
  </div>

	<script> 
    $(document).ready( function () {
        $('#table').DataTable();
        $('#tableTrashed').DataTable();
    });
  </script>

@endsection