routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });

Auth::routes();

Route::get('/', 'Auth\LoginController@index')->name('');

//dashboard
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoriesController');
Route::resource('products', 'ProductsController');
Route::resource('transactions', 'TransactionsController');
Route::resource('shop', 'ShopController');

//add admin
Route::get('addadmin', [
	'uses' => 'HomeController@addAdmin',
	'as' => 'addadmin'
]);

Route::post('registeradmin', [
	'uses' => 'HomeController@registerAdmin',
	'as' => 'registeradmin'
]);	

//my profile
Route::get('myprofile', [
	'uses' => 'HomeController@myProfile',
	'as' => 'myprofile'
]);

Route::post('admineditprofile', [
	'uses' => 'HomeController@editMyProfile',
	'as' => 'admineditprofile'
]);

Route::post('adminchangepassword', [
	'uses' => 'HomeController@changePassword',
	'as' => 'adminchangepassword'
]);

//category

Route::get('/restorecategory/{id}', [
	'uses' => 'CategoriesController@restoreCategory',
	'as' => 'restorecategory'
]);

//products
Route::post('/update_image', 'ProductsController@updateImage')->name('update_image');

Route::get('exportproduct', [
	'uses' => 'ProductsController@exportProduct',
	'as' => 'exportproduct'
]);

Route::post('importexcel', [
	'uses' => 'ProductsController@importExcelfile',
	'as' => 'importexcel'
]);

Route::post('processexcel', [
	'uses' => 'ProductsController@processExcelfile',
	'as' => 'processexcel'
]);

Route::get('/restore/{id}', [
	'uses' => 'ProductsController@restoreProduct',
	'as' => 'restore'
]);

Route::get('/addstock_view/{id}', [
	'uses' => 'ProductsController@viewAddStock',
	'as' => 'addstock_view'
]);

Route::post('addstock', [
	'uses' => 'ProductsController@addStockProduct',
	'as' => 'addstock'
]);

//////////////////////////////////////////////////////////////
//customers
Route::get('customers', [
	'uses' => 'CustomersController@getIndex',
	'as' => 'customers'
]);

Route::post('sendmessage', [
	'uses' => 'CustomersController@sendCustomerEmail',
	'as' => 'sendmessage'
]);

////////////////////////////////////////////////////////////

//orders 
Route::get('orders', [
	'uses' => 'OrdersController@getIndex',
	'as' => 'orders'
]);

Route::get('/processorder/{id}', [
	'uses' => 'OrdersController@processOrder',
	'as' => 'processorder'
]);

Route::get('/deliverorder/{id}', [
	'uses' => 'OrdersController@deliverOrder',
	'as' => 'deliverorder'
]);

Route::get('/rejectorder/{id}', [
	'uses' => 'OrdersController@rejectOrder',
	'as' => 'rejectorder'
]);

Route::get('sendemail', [
	'uses' => 'OrdersController@sendEmail',
	'as' => 'sendemail'
]);

Route::get('/notify/{pid}/{oid}', [
	'uses' => 'OrdersController@notifyOutOfStock',
	'as' => 'notify'
]);

//////////////////////////////////////////////////////////////

//reports
Route::get('reports',[
	'uses' => 'ReportsController@getIndex',
	'as' => 'reports'
]);

Route::post('showreports', [
	'uses' => 'ReportsController@generateReport',
	'as' => 'showreports'
]);

Route::get('/printreport/{datefrom}/{dateto}', [
	'uses' => 'ReportsController@printReport',
	'as' => 'printreport'
]);

Route::get('printreporttoday', [
	'uses' => 'ReportsController@printReportToday',
	'as' => 'printreporttoday'
]);



///////////////////////////////////////////////////////////////
// shop
Route::get('/add-to-cart/{id}', [
	'uses' => 'ShopController@getAddToCart',
	'as' => 'product.addToCart'
]);

Route::get('/addByOne/{id}', [
	'uses' => 'ShopController@getAddByOne',
	'as' => 'product.addByOne'
]);

Route::get('/reduceByOne/{id}', [
	'uses' => 'ShopController@getReduceByOne',
	'as' => 'product.reduceByOne'
]);

Route::get('/remove/{id}', [
	'uses' => 'ShopController@getRemoveItem',
	'as' => 'product.revomeItem'
]);

Route::get('/shopping-cart', [
	'uses' => 'ShopController@getCart',
	'as' => 'product.shoppingCart'
]);

Route::get('/checkout', [
	'uses' => 'ShopController@getCheckout',
	'as' => 'checkout',
	'middleware' => 'auth'
]);

Route::post('/checkout', [
	'uses' => 'ShopController@saveOrder',
	'as' => 'checkout'
]);

Route::post('/cancelorder', [
	'uses' => 'ShopController@cancelOrder',
	'as' => 'cancelorder'
]);

Route::get('/vieworder/{id}', [
	'uses' => 'ShopController@viewOrderList',
	'as' => 'order.vieworder'
]);

Route::get('/category/{id}', [
	'uses' => 'ShopController@filterByCategory',
	'as' => 'shop.category'
]);

Route::post('editprofile', [
	'uses' => 'ShopController@updateProfile',
	'as' => 'editprofile'
]);

Route::post('customerchangepassword', [
	'uses' => 'ShopController@changePassword',
	'as' => 'customerchangepassword'
]);

Route::get('indicatorverify', [
	'uses' => 'ShopController@indicatorVerify',
	'as' => 'indicatorverify'
]);

Route::group(['prefix' => 'user'], function() {

	Route::group(['middleware' => 'guest'], function() {

		Route::get('/customer_register', [
			'uses' => 'ShopController@customerRegister',
			'as' => 'user.customer_register',
		]);

		Route::post('/customer_signup', [
			'uses' => 'ShopController@customerSignup',
			'as' => 'user.customer_signup',
		]);

		Route::get('/customer_login', [
			'uses' => 'ShopController@customerLogin',
			'as' => 'user.customer_login',
		]);

		Route::post('/customer_signin', [
			'uses' => 'ShopController@customerSignin',
			'as' => 'user.customer_signin',
		]);

		Route::get('/verifyaccount/{id}', [
			'uses' => 'ShopController@verifyAccount',
			'as' => 'user.verifyaccount'
		]);

	});
	
	Route::group(['middleware' => 'auth'], function() {

		Route::get('/customer_logout', [
			'uses' => 'ShopController@customerLogout',
			'as' => 'user.customer_logout',
		]);

		Route::get('/customer_orders', [
			'uses' => 'ShopController@customerOrders',
			'as' => 'user.customer_orders',
		]);

		Route::get('/customer_profile', [
			'uses' => 'ShopController@customerProfile',
			'as' => 'user.customer_profile',
		]);

	});

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    //
    use SoftDeletes;

    protected $fillable = [
    	'name',
    	'description',
    	'price',
    	'stock',
    	'user_id',
    	'category_id',
        'image',
    ];

    protected $dates = ['deleted_at'];

    public function category() {
        return $this->belongsTo('App\Category');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Cart;
use Illuminate\Http\Request;
use App\Category;
use Auth;
use DB;
use Session;
use Carbon\Carbon;
use Excel;
use Response;
use App\ExcelImport;
use Storage;

class ProductsController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //
        if (Auth::user()->role_id == 1) {
            $products = Product::whereNull('deleted_at')
                                ->get();

            $categories = Category::whereNull('deleted_at')
                                ->get();

            $trashProduct = DB::table('products')
                                ->whereNotNull('deleted_at')
                                ->get();

            $counterorder = DB::table('transactions')
                            ->where('status', "Pending")
                            ->count();

            $criticalProduct = DB::table('products')
                                    ->where('stock','<=',10)
                                    ->get();
            $countCritical = DB::table('products')
                                    ->where('stock','<=',10)
                                    ->count();

            return view('products.index', ['products' => $products, 'categories' => $categories,
                                            'trashedProduct' => $trashProduct, 'counterorder' => $counterorder,
                                            'critical' => $criticalProduct, 'countcritical' => $countCritical]);
        }
        return back();
    }

    public function store(Request $request)
    {
        //
        if (Auth::user()->role_id == 1) {

            if ($request->hasFile('image')) {
                    
                $filename = $request->file('image')->getClientOriginalName(); // get the original name
                $path = $request->file('image')->storeAs('public', $filename); // store the new image to the store/public

                    if ($path) {
                        $insertProduct = Product::create([
                                            'user_id' => Auth::user()->id,
                                            'name' => $request['name'],
                                            'description' => $request['description'],
                                            'stock' => $request['stock'],
                                            'price' => $request['price'],
                                            'category_id' => $request['category'],
                                            'image' => $filename,
                                        ]);

                        if ($insertProduct) {
                            return back()->with('success','Product added successfully');
                        }
                        return back()->with('errors','Error adding product');

                    }

            }
            else
            {
                $insertProduct = Product::create([
                                    'user_id' => Auth::user()->id,
                                    'name' => $request['name'],
                                    'description' => $request['description'],
                                    'stock' => $request['stock'],
                                    'price' => $request['price'],
                                    'category_id' => $request['category'],
                                ]);

                if ($insertProduct) {
                    return back()->with('success','Product added successfully');
                }
                return back()->with('errors','Error adding product');
            }

        }
        return back();
        
    }

    public function edit(Product $product)
    {
        //
        if (Auth::user()->role_id == 1) {

            $findProduct = Product::find($product->id);

            $selectCategory = Category::where('id', "!=", $findProduct->category_id)
                                    ->get();

            $counterorder = DB::table('transactions')
                            ->where('status', "Pending")
                            ->count();

            return view('products.edit', ['product' => $findProduct, 'categories' => $selectCategory,
                                            'counterorder' => $counterorder]); 
        }
        return back(); 
    }

    public function update(Request $request, Product $product)
    {
        //
        if (Auth::user()->role_id == 1) {
            $updateProduct = Product::where('id',$product->id)
                                    ->update([
                                        'name' => $request['name'],
                                        'category_id' => $request['category'],
                                        'price' => $request['price'],
                                        'stock' => $request['stock'],
                                        'description' => $request['description']
                                    ]);
            if ($updateProduct) {
                return back()->with('success','Product updated successfully.');
            }
            return back()->with('errors','Error updating product.');
        }
        return back(); 
    }

    public function destroy(Product $product)
    {
        //
        if (Auth::user()->role_id == 1) {
            if (Product::find($product->id)->delete()) {
                return back()->with('success','Product deleted successfully.');
            }
            return back()->with('errors','Error deleting product.');
        }
        return back(); 

    }

    public function updateImage(Request $request)
    {
        if (Auth::user()->role_id == 1) {

            if ($request->hasFile('uploadImage')) { // if not empty the post file

                    $productId = $request->input('productId'); // get the id of employee
                    $getImage = Product::find($productId); // get the data of employee

                    $imageName = $getImage->image; // get the avatar name

                        if ($imageName == null) { // if null the avatar column on db / no existing image

                            $filename = $request->file('uploadImage')->getClientOriginalName(); // get the orignal name of image
                            $path = $request->file('uploadImage')->storeAs('public', $filename); // store the image to store/app/public

                                if ($path) { // if success of storing the image to directory
                                    $fileSave = Product::where('id', $productId) // save the name of image to the database
                                                    ->update([
                                                        'image' => $filename
                                                    ]);

                                    if ($fileSave) { // if success of saving to the database
                                        return back()->with('success' , 'Product image updated successfully');
                                    }

                                    return back()->withInput()->with('errors', 'Error update product image (Saving the image name to the database)'); // else not success of saving
                                }

                                return back()->withInput()->with('errors', 'Error update product image (Storing the image to the directory)'); // else not success of storing to directory

                        } else { // if not null the avatar column on db / and has a existing image
                                
                            if (Storage::delete('public/'.$imageName)) { // delete the existing image in the store folder

                                $filename = $request->file('uploadImage')->getClientOriginalName(); // get the original name
                                $path = $request->file('uploadImage')->storeAs('public', $filename); // store the new image to the store/public

                                    if ($path) { // if success of storing the directory
                                        $fileSave = Product::where('id', $productId) // update to the database the new name db
                                                    ->update([
                                                        'image' => $filename
                                                    ]);

                                        if ($fileSave) { // if success of updating new name in db
                                            return back()->with('success' , 'Product image updated successfully');
                                        }

                                        return back()->withInput()->with('errors', 'Error update product image (Saving the image name to the database)'); // else failed updating to db
                                    }

                                    return back()->withInput()->with('errors', 'Error update product image (Storing the new image to the directory)'); // failed to storing to directory
                            }

                            return back()->withInput()->with('errors', 'Error update product image (Deleting the existing image to the directory)'); // failed to delete existing image to directory
                        }

                    
                } else {
                   return "No file selected"; // if no file selected
                }

        }
        return back(); 
           
    }

    public function exportProduct() 
    {          

        $now = Carbon::now('Asia/Manila');
        $datetime = $now->toDateTimeString();
        $date = $now->toDateString();
        $time = $now->toTimeString();

        $headers = array(
            "Content-type" => "text/xlsx",
            "Content-Disposition" => "attachment; filename=Products".$datetime.".xlsx",

resources/views/products/addstock.blade.php
@extends('layouts.app')

@section('content')

	@include('partials.sidebar')

	<main role="main" class="col-md-9 col-lg-9 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

		@include('partials.errors')
        @include('partials.success') 

		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
		  <h1 class="h2"><a href="/products"><i class="fa fa-shopping-cart"></i> Products/</a>Add stock</h1>
		</div>

		<div class="container">
            <div class="row">
              
                <div class="col-md-8 mt-5">

                  <form method="post" action="{{ route('addstock') }}">
                    @csrf
                  <input type="hidden" name="id" value="{{$product->id}}">
                  
                  <div class="row">
                                         
                      <div class="col-md-5">
                        <div class="form-group">
                          <label for="id" class="col-form-label">Product ID:</label>
                          <input type="text" class="form-control bg-white" value="{{ $product->id }}" readonly disabled>
                        </div>
                      </div>

                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="name" class="col-form-label">Product Name:</label>
                          <input type="text" class="form-control bg-white" id="name" value="{{ $product->name }}" readonly disabled>
                        </div>
                      </div>

                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="name" class="col-form-label">Stock:</label>
                          <input type="number" class="form-control bg-white" name="addedstock" required autofocus>
                          <button class="btn btn-primary float-right mt-3" type="submit"><i class="fa fa-plus"></i> Add</button>
                        </div>
                      </div>
            

                    </div>
                  </form>

                </div>

            </div>            
          </div>
	</main>


@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

	@include('partials.sidebar')

	<main role="main" class="col-md-9 col-lg-9 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>

		@include('partials.errors')
        @include('partials.success') 

		<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
		  <h1 class="h2"><a href="/products"><i class="fa fa-shopping-cart"></i> Products/</a>Update product</h1>
		</div>

		<div class="container">
            <div class="row">
              
                <div class="col-md-9 mt-5">

                  <form method="post" action="{{ route('products.update', [$product->id]) }}">
                  <input type="hidden" name="_method" value="put">
                  @csrf
                  <div class="row">
                                         
                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="id" class="col-form-label">Product ID:</label>
                          <input type="text" class="form-control bg-white" id="id" value="{{ $product->id }}" readonly disabled>
                        </div>
                      </div>

                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="company" class="col-form-label">Category:</label>
                          <select class="custom-select form-control" name="category">
                            <option value="{{$product->category_id}}" selected>{{ $product->category->name }}</option>
                            @foreach($categories as $category)
                              <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                          </select>
                        </div>
                      </div>

                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="name" class="col-form-label">Product Name:</label>
                          <input type="text" class="form-control bg-white" name="name" id="name" value="{{ $product->name }}" placeholder="Name" required>
                        </div>
                      </div>

                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="price" class="col-form-label">Price:</label>
                          <input type="number" class="form-control bg-white" name="price" id="price" value="{{ $product->price }}" placeholder="Price" required>
                        </div>
                      </div>

                      <div class="col-md-4">
                        <div class="form-group">
                          <label for="stock" class="col-form-label">Stock:</label>
                          <input type="number" class="form-control bg-white" name="stock" id="stock" value="{{ $product->stock }}" placeholder="Stcok" required>
                        </div>
                      </div>             

                      <div class="col-md-8">
                        <div class="form-group">
                          <label for="description" class="col-form-label">Description:</label>
                          <textarea class="form-control bg-white" rows="3" name="description" id="description" placeholder="Description">{{ $product->description }}</textarea>
                        </div>
                      </div>

                      <div class="col-md-12">
                          <div class="form-group float-right">
                            <button class="btn btn-primary float-right" type="submit"><i class="fa fa-arrow-down"></i> Save</button>
                          </div>
                      </div>

                    </div>
                  </form>

                </div>

                <div class="col-md-2">
                  <div class="col-md-12 border p-0" style="height:160px;">
                    @if($product->image == null)
                      <img src=" {{ asset('storage/no_image.png') }}" class="form-control p-0" style="width:100%; height: 100%;">
                    @else
                      <img src=" {{ asset('storage/') }}/{{ $product->image }}" class="form-control p-0" style="width:100%; height: 100%;">
                    @endif
                  </div>
                  <div class="col-md-12 mt-2 p-0">

                    <form method="post" action="{{ route('update_image') }}" enctype="multipart/form-data" class="d-inline">
                      @csrf
                      <input type="hidden" name="productId" value="{{ $product->id }}">
                      <input type="file" name="uploadImage" class="form-control" id="choose_file" style="display: none;" required>
                      <button class="btn btn-success mt-2" id="save_image" onclick="save_image()" style="display: none;">SAVE</button>
                    
                    </form>

                    <button class="btn btn-primary ml-5" id="edit_image" onclick="edit_image()"><i class="fa fa-pencil-square-o"></i> EDIT</button>
                    <button class="btn btn-danger mt-2" id="cancel_image" onclick="cancel_image()" style="display: none;">CANCEL</button>

                  </div>
                </div>

            </div>            
          </div>
	</main>

  <script>
    //edit function
    function edit_image() {
      $("#save_image").show(500);
      $("#cancel_image").show(500);
      $('#choose_file').show(500);
      $("#edit_image").hide(500);
    }

    //cancel function
    function cancel_image() {
      $("#save_image").hide(500);
      $("#cancel_image").hide(500);
      $("#edit_image").show(500);
      $('#choose_file').hide(500);
    }   
  </script>

@endsection

resources/views/products/import_excel_fields.blade.php
@extends('layouts.app')

@section('content')
    @include('partials.sidebar')
    <main role="main" class="col-md-9 col-lg-9 px-4"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
        
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading"><h3>Parse Excel Data</h3></div>

                        <div class="panel-body mt-5">
                            <form class="form-horizontal" method="POST" action="{{ route('processexcel') }}">
                                {{ csrf_field() }}
                                <input type="hidden" name="excel_data_file_id" value="{{ $excel_data_file->id }}" />

                                <table class="table">
                                    @foreach ($excel_data as $row)
                                        <tr>
                                        @foreach ($row as $key => $value)
                                            <td>{{ $value }}</td>

                                        @endforeach
                                        </tr>
                                    @endforeach
                                </table>

                                <a href="/home" class="btn btn-danger float-right ml-3"><i class="fa fa-times"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary float-right">
                                    <i class="fa fa-arrow-down"></i> Import Data
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection